---
- name: gather facts on local helpers installed
  shell: 'yay --version'
  register: yay_cmd
  failed_when: false
  changed_when: false

- block:
  - name: clone yay aur helper package
    git:
      repo: 'https://aur.archlinux.org/yay.git'
      dest: '/tmp/yay'
      version: 'master'

  - name: makepkg aur helper
    shell: 'makepkg -si --noconfirm'
    args:
      chdir: '/tmp/yay'
  when: yay_cmd.rc > 0
