---
# tasks file for bootstrap-ansible-arch
# - name: ensure python is present
#   raw: test -e /usr/bin/python || (pacman --noconfirm -S python)
#   become: true
#   changed_when: false
- name: upgrade packages & package cache
  when: arch_bootstrap_upgrade_pkgs
  become: true
  pacman:
    update_cache: true
    upgrade: true

- name: important ansible utils (curl,wget,git) are present
  become: true
  package:
    name:
      - curl
      - wget
      - git
    state: present

- name: setup system for AUR
  block:
  - name: makepkg dependencies installed
    become: true
    package:
      name:
        - binutils
        - make
        - gcc
        - fakeroot

- name: aur_builder user used for aur packagers present
  become: true
  user:
    name: aur_builder
    group: wheel

- name: aur_builder sudo access to pacman
  become: true
  lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: true
    validate: 'visudo -cf %s'

- name: clone aur helper package
  git:
    repo: 'https://github.com/kewlfft/ansible-aur.git'
    dest: '{{ ansible_env.HOME }}/.ansible/plugins/modules/aur'
    version: 'v0.23'
  when: arch_bootstrap_aur_enabled
