---
# tasks file for bootstrap-ansible-arch
# - name: ensure python is present
#   raw: test -e /usr/bin/python || (pacman --noconfirm -S python)
#   become: true
#   changed_when: false
- name: aur_builder user used for aur packagers present
  become: true
  user:
    name: aur_builder
    group: wheel

- name: curl is present
  become: true
  package:
    name: curl
    state: present

- name: wget is present
  become: true
  package:
    name: wget
    state: present
